//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaksi
    {
        public int id { get; set; }
        public int id_kendaraan { get; set; }
        public int id_member { get; set; }
        public int id_karyawan { get; set; }
        public System.DateTime TanggalMenyewa { get; set; }
        public string TanggalAkhir { get; set; }
        public string WaktuMenyewa { get; set; }
        public string WaktuSewa { get; set; }
        public string JumlahBayar { get; set; }
    
        public virtual Karyawan Karyawan { get; set; }
        public virtual Kendaraan Kendaraan { get; set; }
        public virtual Member Member { get; set; }
    }
}
